#!/bin/bash

# start_api is for users to launch the API
# stack into their account using the release
# package from GitHub

CONFIG_JSON=$( cat config.json | jq )

STACK_NAME=$( jq -r  '.aws.cloudformation.stack_name' <<< "${CONFIG_JSON}" )

ARTIFACT_BUCKET=$( jq -r  '.aws.s3.artifact_bucket' <<< "${CONFIG_JSON}" )
DATABASE_BUCKET=$( jq -r  '.aws.s3.database_bucket' <<< "${CONFIG_JSON}" )

aws s3 mv database.zip s3://$ARTIFACT_BUCKET/
aws s3 mv query.zip s3://$ARTIFACT_BUCKET/
aws s3 mv setup.zip s3://$ARTIFACT_BUCKET/

HTTP_SECURITY_KEY=$(uuidgen)

aws cloudformation deploy \
	--template-file cft.yaml \
	--s3-bucket $ARTIFACT_BUCKET \
	--stack-name $STACK_NAME \
	--parameter-overrides \
		StackName=$STACK_NAME \
		HTTPSecurityKey=$HTTP_SECURITY_KEY \
		ArtifactBucket=$ARTIFACT_BUCKET  \
		DatabaseBucket=$DATABASE_BUCKET \
	--capabilities CAPABILITY_NAMED_IAM \
	--no-fail-on-empty-changeset

echo 'launched stack resources'