#!/bin/bash

BUCKET_NAME=$1

if [ -z "$BUCKET_NAME" ];
then
	echo "Bucket name argument not provided"
	exit 1
fi

BUCKET_RESOURCE="arn:aws:s3:::$BUCKET_NAME"
OBJECTS_RESOURCE="$BUCKET_RESOURCE/*"

POLICY_DOCUMENT=$( jq -n \
	--arg bucket_resource $BUCKET_RESOURCE \
	--arg objects_resource $OBJECTS_RESOURCE \
	'{
		"Version": "2012-10-17",
		"Statement": [
			{
				"Effect": "Allow",
				"Principal": {
					"AWS": "arn:aws:iam::468628870724:role/cheesesteak-acct-role"
				},
				"Action": [
					"s3:PutBucketNotification",
					"s3:GetBucketNotification"
				],
				"Resource": $bucket_resource
			},
			{
				"Effect": "Allow",
				"Principal": {
					"AWS": "arn:aws:iam::468628870724:role/cheesesteak-db-role"
				},
				"Action": [
					"s3:GetObject"
				],
				"Resource": $objects_resource
			}
		]
	}'
)

echo $POLICY_DOCUMENT > policy.json

ID=$(uuidgen)

aws s3api put-bucket-policy \
	--bucket $BUCKET_NAME \
	--policy file://policy.json

rm policy.json